### ISSUE TITLE
Reconnecting a broken socket

### ISSUE THREAD

**Issue by ondras** [ondras/cyp#13]
https://github.com/ondras/cyp/issues/11#issuecomment-626217952

**Comment by ondras** [comment]
@stefanroellin, please try updating to the latest `master`. The web UI shall be able to reconnect to a restarted CYP (or MPD) now. Also, if some component is not running/answering at all, the user will be notified with an alertbox.

**Comment by stefanroellin** [comment]
I did short test. As you write, the web UI was able to reconnect, after mpd was stopped and started again. 
Thanks for your work!
