### ISSUE TITLE
How to build JS and CSS?

### ISSUE THREAD

**Issue by JFox-sk** [ondras/cyp#15]
Hi,
please, can you provide some instructions about how to build JavaScript (app/js/*.js > app/cyp.js) and CSS (app/css/*.less > app/cyp.css)?
Thank you!

**Comment by ondras** [comment]
Hi @JFox-sk,

you need to install `make` and `npm`. Then, in the checked out repository:

```sh
$ npm i
$ make
```

**Comment by JFox-sk** [comment]
Ouu, I did not notice Makefile :-) Thank you!
