### ISSUE TITLE
JS error in Search for Safari 12.1

### ISSUE THREAD

**Issue by jgillman** [ondras/cyp#2]
I've only tested on Safari 12.1 and Chrome 74 on macOS 10.14.4. Works nicely in Chrome but I'm getting the below JS error when the app loads in Safari:

```
[Error] Unhandled Promise Rejection: TypeError: function is not a constructor (evaluating 'super()')
	Search (search.js:9)
	init (library.js:109)
	(anonymous function) (app.js:58)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
```

**Comment by ondras** [comment]
Nice find!

Looks like Safari is not happy with extending the native `EventTarget`. The offending `super()` call is necessary, though -- both Firefox and Chrome correctly require it, as it is mandatory for derived classes.

I will try to find some more info on this.

**Comment by ondras** [comment]
This is the bug you ran into: https://bugs.webkit.org/show_bug.cgi?id=174313
