### ISSUE TITLE
Artist now shown in CurrentSong or Queue

### ISSUE THREAD

**Issue by Doedelpumpe** [ondras/cyp#21]
As i installed the cyp the artists were not showing at current song overview or inside the queue.

In the /app/cyp.js i changed line 899 (function subtitle)

`data["Artist"] && tokens.push(data["Artist"]);`
to
`data["AlbumArtist"] && tokens.push(data["AlbumArtist"]);`

and it got fixed.

**Comment by ondras** [comment]
Hi @Doedelpumpe,

thanks for the suggestion. It should be fixed now.
