### ISSUE TITLE
Playlist - view contents

### ISSUE THREAD

**Issue by netmindz** [ondras/cyp#28]
Is it not possible to see the contents of a playlist - only add to the Queue?

**Comment by ondras** [comment]
Yes, there is no "playlist contents" view. But I suppose that adding an "»" icon to the end of the playlist row (similar to Library items) might be a good way to implement this functionality? Would that work for you, @netmindz ?

**Comment by netmindz** [comment]
Sounds good

**Comment by ondras** [comment]
So I added the ability to inspect playlists and rewrote the app in TypeScript in the meantime ;-)
