### ISSUE TITLE
FR: Option to set default server

### ISSUE THREAD

**Issue by netmindz** [ondras/cyp#29]
While selecting the server via the query string is possible, would it be possible to add an environment variable to allow you to set the default server?

**Comment by ondras** [comment]
Good idea. Please open the issue in the [ws2mpd](https://github.com/ondras/ws2mpd) repository, because that library is used to connect to MPD.

**Comment by netmindz** [comment]
Done https://github.com/ondras/ws2mpd/issues/1

**Comment by netmindz** [comment]
Feature now exists, so can you now reopen this issue please

**Comment by ondras** [comment]
Why do you want to reopen? I mentioned these new env vars (for ws2mpd) in [the README](https://github.com/ondras/cyp#installation), so you just install the latest ws2mpd and use them.

I also bumped the ws2mpd dependency version here in package.json, so when you pull CYP, `npm i` shall install the proper dependency.

**Comment by netmindz** [comment]
Ah is wasn't clear that the web app itself didn't need any changes once then library was updated
