### ISSUE TITLE
Is this able to work with yt-dlp?

### ISSUE THREAD

**Issue by bitingsock** [ondras/cyp#32]

**Comment by ondras** [comment]
Maybe? I have no idea, honestly. No experience with `yt-dlp`.

There was a somewhat related discussion in https://github.com/ondras/cyp/issues/24#issuecomment-1830468902

You might want to check the `youtube-dl` arguments used to see if these work with `yt-dlp` as well: [searching](https://github.com/ondras/cyp/blob/master/index.js#L28), [downloading](https://github.com/ondras/cyp/blob/master/index.js#L46)

**Comment by bitingsock** [comment]
pretty sure it is exactly the same.
```yt-dlp -j ytsearch2:test``` for example produces the attached json
[out.txt](https://github.com/ondras/cyp/files/15192215/out.txt)
If there was a way to specify ```youtube-dl```'s path it should just work.

**Comment by ondras** [comment]
I just pushed a commit that uses the `YOUTUBE` environment variable to specify the youtube downloading program (defaults to `youtube-dl`). Please try with `yt-dlp` and let me know how that works for you.

**Comment by bitingsock** [comment]
Awesome, will do.

**Comment by bitingsock** [comment]
Seems to work, although at least under Windows I had to remove the ```'``` escape from the search query(as well as other shell related changes). It does download correctly though. However, mpd says it's an ```ffmpeg: Unsupported audio codec``` though I suspect that is a Windows mpd issue.
