### ISSUE TITLE
Documentation how to specify remote server

### ISSUE THREAD

**Issue by kannes** [ondras/cyp#6]
By default cyp seems to try to find the mpd server on localhost. A common scenario are mpd servers hosted somewhere else in the network.

If there is a straightforward way to configure a remote mpd server host please document it :)

**Comment by ondras** [comment]
Hi @kannes,

sorry for the lack of documentation! The actual connection to MPD happens at https://github.com/ondras/ws2mpd/blob/master/index.js#L10 (ws2mpd is the library internally used to translate WebSocket communication to the MPD protocol) and the hostname seems to be driven via the `host` query string parameter (defaulting to `0:6600`).

This applies to the initial WebSocket request, which is initiated from https://github.com/ondras/cyp/blob/master/app/js/lib/mpd.js#L146 -- and the URL does not seem to be configurable (it only includes a `ticket` value that acts as a CSRF prevention token).

So, I would say that it is currently not possible to connect to another MPD host. If you feel that such feature might be useful, please let me know and I will implement it.

**Comment by ondras** [comment]
Hi @kannes,

you can now specify the MPD address using the `server` query string parameter.

**Comment by gerroon** [comment]
It would be nice to be able to change MPD profiles for sure. I like to run MPDs on different servers.

**Comment by ondras** [comment]
> It would be nice to be able to change MPD profiles for sure.

Right, that is why you specify the MPD URL in a query string parameter. So you can have multiple cyp URLs, one for every MPD you control.

**Comment by kannes** [comment]
Sweet, thank you!
