### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by gerroon** [ondras/cyp#8]
is it possible to provide a proxyable Docker image for this?

thanks

**Comment by ondras** [comment]
It is possible, indeed! Unfortunately, I do not use Docker and my Docker experience is very limited. Perhaps someone more skilled can chime in and provide a PR?

Alternatively, I can try this on my own, but it might take some time for me to get the whole ifrastructure up and running.

**Comment by gerroon** [comment]
No problem, thanks for your interest in providing it. Npm can be complicatred for regular users like me.

**Comment by ondras** [comment]
This is my first attempt at https://github.com/ondras/cyp#instalation---docker .

**Comment by gerroon** [comment]
Thanks, I will try it. Is it possible to change the default running port?

**Comment by ondras** [comment]
Apparently [yes](https://github.com/ondras/cyp/blob/master/index.js#L3), by passing the number as a command line argument:

```node index.js 12345```

**Comment by gerroon** [comment]
I meant for Docker

**Comment by ondras** [comment]
> I meant for Docker

Yeah, that is what you pass as additional command line arguments to `docker run`:

```bash
docker run --network=host cyp node index.js 12345
```

**Comment by gerroon** [comment]
thanks I will try it, maybe this should be mentioned in the front paeg?

**Comment by gerroon** [comment]
Ok I was wrong about the port, it seems to change the exposed port.

**Comment by gerroon** [comment]
Ok just hit an issue with youtube. I made a search and hit this error.

`spawn youtube-dl ENOENT`

**Comment by ondras** [comment]
> Ok just hit an issue with youtube. I made a search and hit this error.
> 
> `spawn youtube-dl ENOENT`

I updated the whole process and mentioned it in the documentation.

1. The image now includes youtube-dl (please run `docker build` to re-build)
1. You need to bind-mount the `_youtube` directory when using `docker run` (this is mentioned in the README)
1. You need to expose the `_youtube` directory to MPD's library (in the README as well)
1. The port is now set via the `PORT` env variable (in the README as well)

**Comment by gerroon** [comment]
I can confirm that the new update resolves those issues.
